# Generated by Django 5.0.3 on 2024-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=256)),
                ('total_player', models.IntegerField()),
                ('vanue', models.CharField(blank=True, max_length=256, null=True)),
                ('batter', models.IntegerField()),
                ('bowler', models.IntegerField()),
                ('wicket_kipper', models.IntegerField()),
                ('captain_name', models.CharField(max_length=256)),
            ],
        ),
    ]
